# Generated by Django 5.0.4 on 2025-05-06 23:19

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[main_app.validators.PositiveNumberValidator('The budget must be non-negative and over 0!')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[main_app.validators.PositiveNumberValidator('The expense must be non-negative and over 0!')]),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[main_app.validators.PositiveNumberValidator('The expense must be non-negative and over 0!')]),
        ),
    ]
